### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by Skyline404** [Drapersniper/Qbitrr#59]
I'm using docker version of the script, mounted db files like this:
```
   - ${DOCKERDIR}/sonarr/config/sonarr.db:/sonarr/sonarr.db:ro 
   - ${DOCKERDIR}/radarr/config/radarr.db:/radarr/radarr.db:ro
```
but getting errors on container start:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 2985, in run_search_loop
    self.db_update()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 1295, in db_update
    self.db_update_todays_releases()
  File "/usr/local/lib/python3.10/site-packages/qBitrr/arss.py", line 1280, in db_update_todays_releases
    for series in self.model_arr_file.select().where(
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6923, in __iter__
    self.execute()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 1911, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 1982, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2155, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3157, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: attempt to write a readonly database
```

**Comment by Drapersniper** [comment]
Hmm in that case the files should still have read access .. can you cd up one directory and run `ls -la .` I'm wondering what the perms are in the actual folders

**Comment by Drapersniper** [comment]
Due to no further reports, will be closing this. Please reopen if it happens again, but it seems like a permission issue.
